# frozen_string_literal: true

Rails.application.routes.draw do
  # Health check
  get "up" => "rails/health#show", as: :rails_health_check

  # PWA files
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Authentication (generated by Rails 8)
  resource :session
  resources :passwords, param: :token

  # API routes
  namespace :api do
    resources :terminals, only: [:index, :show]

    resources :trips, only: [:show] do
      collection do
        get :search
      end
      member do
        get :seats
      end
    end

    resources :reservations, param: :locator, only: [:create, :show, :update, :destroy] do
      member do
        post :checkout
      end
    end

    resources :payment_intents, param: :external_id, only: [:show] do
      member do
        post :start
      end
    end

    namespace :webhooks do
      post :fintoc_mock
    end
  end

  # Admin routes
  namespace :admin do
    root to: "dashboard#index"

    resources :terminals
    resources :routes
    resources :buses
    resources :trips do
      member do
        get :occupancy
      end
    end
    resources :reservations, only: [:index, :show] do
      member do
        post :cancel
      end
      collection do
        get :export
      end
    end
  end

  # SPA fallback - Vue app handles all other routes
  root "home#index"
  get "*path", to: "home#index", constraints: ->(req) { !req.xhr? && req.format.html? }
end
